-- UP
CREATE TABLE IF NOT EXISTS "logs" ("id" UUID , "title" TEXT, "type" VARCHAR(255), "description" TEXT, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));;

CREATE TABLE IF NOT EXISTS "files" ("id" UUID , "key" VARCHAR(255) UNIQUE, "isPublic" BOOLEAN DEFAULT false, "data" BYTEA, "s3Key" VARCHAR(255), "name" VARCHAR(255), "storageType" VARCHAR(255), "encoding" VARCHAR(255), "mimetype" VARCHAR(255), "size" BIGINT, "md5" VARCHAR(255), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));;

CREATE TABLE IF NOT EXISTS "image_files" ("id" UUID , "key" VARCHAR(255) UNIQUE, "nameDisplayed" VARCHAR(255), "fileId" UUID REFERENCES "files" ("id") ON DELETE SET NULL ON UPDATE CASCADE, "isPublic" BOOLEAN DEFAULT false, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));;

CREATE TABLE IF NOT EXISTS "systems" ("id" UUID , "isSetupFinished" BOOLEAN, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));;

CREATE TABLE IF NOT EXISTS "users" ("id" UUID , "email" VARCHAR(255) UNIQUE, "emailVerified" BOOLEAN DEFAULT false, "emailVerificationCode" VARCHAR(255), "verificationCodeEmailSentDate" TIMESTAMP WITH TIME ZONE, "password" VARCHAR(255), "failedLoginAttempts" INTEGER DEFAULT 0, "lastFailedLoginAttempt" TIMESTAMP WITH TIME ZONE, "loginProviders" JSONB DEFAULT '[]', "firstName" VARCHAR(255), "lastName" VARCHAR(255), "photoId" UUID REFERENCES "image_files" ("id") ON DELETE SET NULL ON UPDATE CASCADE, "status" VARCHAR(255) DEFAULT 'Live', "notes" TEXT, "role" VARCHAR(255) DEFAULT 'User', "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));;

CREATE TABLE IF NOT EXISTS "user_sessions" ("id" UUID , "userId" UUID REFERENCES "users" ("id") ON DELETE SET NULL ON UPDATE CASCADE, "sessionId" VARCHAR(255) UNIQUE, "ip" VARCHAR(255), "userAgent" VARCHAR(255), "expiresDate" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));;

CREATE TABLE IF NOT EXISTS "posts" ("id" UUID , "key" VARCHAR(255) UNIQUE, "title" TEXT, "description" TEXT, "content" TEXT, "publishedDate" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));;

CREATE TABLE IF NOT EXISTS "comments" ("id" UUID , "content" TEXT, "postId" UUID REFERENCES "posts" ("id") ON DELETE SET NULL ON UPDATE CASCADE, "authorId" UUID REFERENCES "users" ("id") ON DELETE SET NULL ON UPDATE CASCADE, "publishedDate" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));;

-- DOWN
DROP TABLE IF EXISTS "comments" CASCADE;
DROP TABLE IF EXISTS "posts" CASCADE;
DROP TABLE IF EXISTS "user_sessions" CASCADE;
DROP TABLE IF EXISTS "users" CASCADE;
DROP TABLE IF EXISTS "systems" CASCADE;
DROP TABLE IF EXISTS "image_files" CASCADE;
DROP TABLE IF EXISTS "files" CASCADE;
DROP TABLE IF EXISTS "logs" CASCADE;
